# Trigger is
name: CI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches tags like v1.0.20, v2.3.100, etc.
  workflow_dispatch: # Allows manual triggering in GitHub

jobs:
  run-codecov:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the current codebase
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run the build script (includes coverage generation)
      - name: Run build script
        run: npm run build

      - name: List files in dist after build
        run: ls -al ./dist

      # Step 5: Upload coverage to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: code4ward/JSOI

      - name: List files in dist after coverage
        run: ls -al ./dist

      # Step 6: Publish to npm
      - name: Publish to npm
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use npm token from repository secrets
        run: npm publish