# This workflow is triggered when a tag is added to the gh-pages branch signaling a new release is published.
# From this condition we should trigger code coverage run and build and publish to NPM.
name: publish-on-tag-in-gh-pages

on:
  push:
    tags:
      - 'gh-pages/*' # Trigger on tags created in the gh-pages branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/' # Ensures npm CLI points to npm

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build Distribution
        run: npm run build

      # Step 5: Upload coverage to Codecov
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: code4ward/JSOI

      # Step 6: Publish to npm
      - name: Publish to npm
        working-directory: ./dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # Use npm token from repository secrets
        run: npm publish